import type { Metadata } from 'next';
import { QueryProvider } from '@/shared/tanstack/providers';
import './globals.css';

export const metadata: Metadata = {
  title: 'alaedev-portfolio',
  description: 'Generated by zakarya',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
