/**
 * API Endpoints
 *
 * All endpoint base paths in one place.
 * Generated by zakarya — add new endpoints here or run:
 *   zakarya generate feature <name>
 */

export const ENDPOINTS = {
  // [zakarya:inject:endpoints]
  AUTH: '/auth',
} as const;

export type EndpointKey = keyof typeof ENDPOINTS;
